// demo-solid/ItemDetail.tsx
import {useQuery} from '@rocicorp/zero/solid';
import {Show} from 'solid-js';
import styles from '../demo/ItemDetail.module.css';
import {queries} from '../demo/queries.ts';

const dateFormatter = new Intl.DateTimeFormat(undefined, {
  dateStyle: 'long',
  timeStyle: 'medium',
});

type Props = {
  id: string;
  onClose: () => void;
};

export function ItemDetail(props: Props) {
  const [item, details] = useQuery(() =>
    queries.item.getSingleQuery({id: props.id}),
  );

  return (
    <div class={styles.panel}>
      <button class={styles.close} onClick={props.onClose} aria-label="Close">
        X
      </button>
      <Show
        when={item()}
        fallback={
          <p class={styles.empty}>
            {details().type === 'complete'
              ? `Item not found. ${props.id}`
              : details().type === 'error'
                ? `Error loading item. ${props.id}`
                : 'Loading...'}
          </p>
        }
      >
        {row => (
          <>
            <h2 class={styles.title}>{row().title}</h2>
            <dl class={styles.meta}>
              <dt>ID</dt>
              <dd>{row().id}</dd>
              <dt>Created</dt>
              <dd>{dateFormatter.format(row().created)}</dd>
              <dt>Modified</dt>
              <dd>{dateFormatter.format(row().modified)}</dd>
            </dl>
            <p class={styles.description}>{row().description}</p>
          </>
        )}
      </Show>
    </div>
  );
}

// demo/ItemDetail.tsx
import {useQuery} from '@rocicorp/zero/react';
import React from 'react';
import styles from './ItemDetail.module.css';
import {queries} from './queries.ts';

const dateFormatter = new Intl.DateTimeFormat(undefined, {
  dateStyle: 'long',
  timeStyle: 'medium',
});

type Props = {
  id: string;
  onClose: () => void;
};

export function ItemDetail({id, onClose}: Props): React.ReactNode {
  const [item, {type}] = useQuery(queries.item.getSingleQuery({id}));

  let content: React.ReactNode;

  if (!item) {
    switch (type) {
      case 'complete':
        content = <p className={styles.empty}>Item not found. {id}</p>;
        break;
      case 'error':
        content = <p className={styles.empty}>Error loading item. {id}</p>;
        break;
      default:
        content = <p className={styles.empty}>Loading…</p>;
    }
  } else {
    content = (
      <>
        <h2 className={styles.title}>{item.title}</h2>
        <dl className={styles.meta}>
          <dt>ID</dt>
          <dd>{item.id}</dd>
          <dt>Created</dt>
          <dd>{dateFormatter.format(item.created)}</dd>
          <dt>Modified</dt>
          <dd>{dateFormatter.format(item.modified)}</dd>
        </dl>
        <p className={styles.description}>{item.description}</p>
      </>
    );
  }

  return (
    <div className={styles.panel}>
      <button className={styles.close} onClick={onClose} aria-label="Close">
        ✕
      </button>
      {content}
    </div>
  );
}
