// demo/main.tsx
import {ZeroProvider} from '@rocicorp/zero/react';
import {createRoot} from 'react-dom/client';
import {Demo} from './Demo.tsx';
import './index.css';
import {mutators} from './mutators.ts';
import {schema} from './schema.ts';

const userID = import.meta.env.VITE_PUBLIC_USER_ID ?? 'anon';
const cachePort = import.meta.env.VITE_PUBLIC_CACHE_PORT ?? '5858';
const url = new URL(window.location.href);
const apiBase = `${url.origin}/api/zero`;

createRoot(document.getElementById('root')!).render(
  <ZeroProvider
    schema={schema}
    mutators={mutators}
    userID={userID}
    cacheURL={`${url.protocol}//${url.hostname}:${cachePort}`}
    mutateURL={`${apiBase}/mutate`}
    queryURL={`${apiBase}/query`}
  >
    <Demo />
  </ZeroProvider>,
);

// demo-solid/main.tsx
import {ZeroProvider} from '@rocicorp/zero/solid';
import {render} from 'solid-js/web';
import {mutators} from '../demo/mutators.ts';
import {schema} from '../demo/schema.ts';
import {App} from './App.tsx';
import '../demo/index.css';

const userID = import.meta.env.VITE_PUBLIC_USER_ID ?? 'anon';
const cachePort = import.meta.env.VITE_PUBLIC_CACHE_PORT ?? '5858';
const url = new URL(window.location.href);
const apiBase = `${url.origin}/api/zero`;

render(
  () => (
    <ZeroProvider
      schema={schema}
      mutators={mutators}
      userID={userID}
      cacheURL={`${url.protocol}//${url.hostname}:${cachePort}`}
      mutateURL={`${apiBase}/mutate`}
      queryURL={`${apiBase}/query`}
    >
      <App />
    </ZeroProvider>
  ),
  document.getElementById('root')!,
);
